#previews:
#  generation: manual
#  expireAfterDays: 2

databases:
  - name: site-db
    plan: basic-1gb
    # previewPlan: basic-256mb
    databaseName: tramline_site_production
    user: tramline
    postgresMajorVersion: "14"

services:
  - type: web
    plan: pro
    # previewPlan: standard
    name: site-web
    runtime: ruby
    buildCommand: ./bin/render.build
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: false
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 80
      targetMemoryPercent: 85
    envVars:
      - key: HOSTNAME
        fromService:
          type: web
          name: site-web
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: site-db
          property: connectionString
      - key: SIDEKIQ_REDIS_URL
        fromService:
          type: redis
          name: site-redis
          property: connectionString
      - key: DEFAULT_REDIS_URL
        fromService:
          type: redis
          name: site-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: worker
    name: site-jobs
    plan: standard
    # previewPlan: starter
    runtime: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    autoDeploy: false
    envVars:
      - key: HOSTNAME
        fromService:
          type: web
          name: site-web
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: site-db
          property: connectionString
      - key: SIDEKIQ_REDIS_URL
        fromService:
          type: redis
          name: site-redis
          property: connectionString
      - key: DEFAULT_REDIS_URL
        fromService:
          type: redis
          name: site-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: redis
    plan: starter
    # previewPlan: free
    name: site-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
