default: &default
  url: <%= ENV.fetch("DEFAULT_REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *default
  adapter: async

test:
  <<: *default
  adapter: test

production:
  <<: *default
  adapter: redis
  channel_prefix: site_production
