service: tramline
image: ghcr.io/tramlinehq/tramline-web

builder:
  arch: amd64
  dockerfile: web.Dockerfile
  cache:
    type: gha
    options: mode=max
    image: app-build-cache
  # remote: ssh://sam-staging-local@35.209.23.61:22
  local: true
  secrets:
    - RAILS_MASTER_KEY

servers:
  web:
    hosts:
      - 35.209.23.61
    labels:
      traefik.http.routers.tramline.rule: "Host(`35.209.23.61`)"
    options:
      tty: true
    cmd: bundle exec puma -C config/puma.rb

  worker:
    hosts:
      - 35.209.23.61
    options:
      tty: true
    cmd: bundle exec sidekiq

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: sam-staging-local
  key_data: [ $SSH_PRIVATE_KEY ]

proxy:
  app_port: 3000

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - REDIS_URL
    - SSH_PRIVATE_KEY
    - KAMAL_REGISTRY_PASSWORD
    - DESCOPE_PROJECT_ID
    - DESCOPE_MANAGEMENT_KEY
    - KAMAL_REGISTRY_USERNAME
    - ANONYMIZE_SOURCE_DB_HOST
    - ANONYMIZE_SOURCE_DB_NAME
    - ANONYMIZE_SOURCE_DB_PASSWORD
    - ANONYMIZE_SOURCE_DB_USER
    - DEFAULT_REDIS_URL
    - SESSION_REDIS_URL
    - SIDEKIQ_REDIS_URL
    - APP_REDIRECT_MAPPING_JSON
    - HOST_NAME
    - SESSION_TIMEOUT_IN_MINUTES
    - SIDEKIQ_CONCURRENCY
    - SIDEKIQ_TIMEOUT
    - BILLING_URL
    - APPLELINK_URL
    - INTERCOM_APP_ID
    - JUNE_ANALYTICS_KEY
    - SENTRY_DSN
    - FRONTEND_SENTRY_DSN
    - SENTRY_SECURITY_HEADER_ENDPOINT
    - DISALLOWED_SIGN_UP_DOMAINS
    - CSP_REPORT_ONLY
    - CSP_CONNECT_SRC_URIS
    - DESCOPE_MANAGEMENT_KEY
    - DESCOPE_PROJECT_ID
  clear:
    RAILS_ENV: production
    RAILS_PIPELINE_ENV: staging

volumes:
  - "db_data:/var/lib/postgresql/data"
  - "redis_data:/data"

accessories:
  db:
    image: postgres:14
    host: 35.209.23.61
    port: 5432
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tramline_staging
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    host: 35.209.23.61
    port: 6379
    volumes:
      - redis_data:/data
