service: tramline
image: ghcr.io/tramlinehq/tramline-web

servers:
  web:
    hosts:
      - 35.209.23.61
    options:
      tty: true
    roles:
      - web

  worker:
    hosts:
      - 35.209.23.61
    options:
      tty: true
    roles:
      - worker

proxy:
  app_port: 3000

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - REDIS_URL
  clear:
    RAILS_ENV: production
    RACK_ENV: production

volumes:
  - "db_data:/var/lib/postgresql/data"
  - "redis_data:/data"

accessories:
  db:
    image: postgres:14
    host: 35.209.23.61
    port: 5432
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tramline_staging
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    host: 35.209.23.61
    port: 6379
    volumes:
      - redis_data:/data

hooks:
  setup:
    - bin/rails db:prepare
    - bin/rails assets:precompile
