name: Deploy to GCP Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: # TODO: Remove this once we are ready to merge
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      SERVER_ADDR: 35.209.23.61
      DOCKER_BUILDKIT: 1
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_STAGING_GCP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING_GCP }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD_STAGING_GCP }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_STAGING_GCP }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ vars.GCP_SERVICE_ACCOUNT_KEY_STAGING_GCP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true
          cache-version: "tools-v1-${{ runner.os }}"
        env:
          BUNDLE_WITHOUT: "default development test"
          RAILS_ENV: production

      #   - name: Set up Docker Buildx for cache
      #     uses: docker/setup-buildx-action@v3

      #   - name: Expose GitHub Runtime for cache
      #     uses: crazy-max/ghaction-github-runtime@v3

      - name: Decode and validate GCP Service Account Key
        run: |
          # Create the key file
          echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > ${{ github.workspace }}/gcp-key.json
          echo "" >> ${{ github.workspace }}/gcp-key.json

          # Validate the JSON
          if ! jq -e . ${{ github.workspace }}/gcp-key.json > /dev/null; then
            echo "Error: Invalid JSON in service account key"
            exit 1
          fi

          # Show file info
          ls -la ${{ github.workspace }}/gcp-key.json

      - name: Authenticate GCloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ github.workspace }}/gcp-key.json

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: $GCP_PROJECT_ID

      - name: Check GCloud CLI auth
        run: gcloud info

      - name: Install Kamal
        run: gem install kamal -v 2.5.3

      - name: Deploy with Kamal
        run: kamal deploy
