name: Deploy to GCP Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: # TODO: Remove this once we are ready to merge
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    env:
      SERVER_ADDR: 35.209.23.61
      DOCKER_BUILDKIT: 1
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_STAGING_GCP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING_GCP }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      KAMAL_REGISTRY_USERNAME: tramlinehq
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_STAGING_GCP }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ vars.GCP_SERVICE_ACCOUNT_KEY_STAGING_GCP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true
          cache-version: "tools-v1-${{ runner.os }}"
        env:
          BUNDLE_WITHOUT: "default development test"
          RAILS_ENV: production

      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Authenticate GCloud CLI
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_ID_STAGING_GCP }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@decoded-theme-355014.iam.gserviceaccount.com

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_STAGING_GCP }}

      - name: Check GCloud CLI auth
        run: gcloud info

      - name: Install Kamal
        run: gem install kamal -v 2.5.3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_STAGING_GCP }}

      - name: Disable Git safe directory check
        run: git config --global --add safe.directory '*'

      - name: Login to registry
        run: kamal registry login
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD_STAGING_GCP }}
          KAMAL_REGISTRY_USERNAME: tramlinehq

      - name: Deploy with Kamal
        run: kamal deploy
