name: Deploy to GCP Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: # TODO: Remove this once we are ready to merge
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    env:
      SERVER_ADDR: 35.209.23.61
      DOCKER_BUILDKIT: 1
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_STAGING_GCP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING_GCP }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD_STAGING_GCP }}
      KAMAL_REGISTRY_USERNAME: tramlinehq
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_STAGING_GCP }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ vars.GCP_SERVICE_ACCOUNT_KEY_STAGING_GCP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true
          cache-version: "tools-v1-${{ runner.os }}"
        env:
          BUNDLE_WITHOUT: "default development test"
          RAILS_ENV: production

      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Authenticate GCloud CLI
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_ID_STAGING_GCP }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@decoded-theme-355014.iam.gserviceaccount.com

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_STAGING_GCP }}

      - name: Check GCloud CLI auth
        run: gcloud info

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.KAMAL_REGISTRY_PASSWORD_STAGING_GCP }} | docker login ghcr.io -u tramlinehq -p ${{ secrets.KAMAL_REGISTRY_PASSWORD_STAGING_GCP }}

      - name: Install Kamal
        run: gem install kamal -v 2.5.3

      - name: Logout from docker
        run: docker logout ghcr.io

      - name: Set up SSH connection
        run: |
          # Create SSH directory and write the private key
          mkdir -p ~/.ssh && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          # Enable current SSH key
          eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa
          # Add the server to known_hosts (use `-p 2222` for custom port if needed)
          ssh-keyscan $SERVER_ADDR >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING_GCP }}

      - name: Deploy with Kamal
        run: kamal deploy
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD_STAGING_GCP }}
          KAMAL_REGISTRY_USERNAME: tramlinehq
          SERVER_ADDR: 35.209.23.61
          DOCKER_BUILDKIT: 1
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_STAGING_GCP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING_GCP }}
