name: Publish Web Docker Image

on:
  push:
    branches: [main]
  pull_request: # TODO: Remove this once we are ready to merge
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tramlinehq/tramline-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Ruby and Bundler versions
        id: versions
        run: |
          echo "ruby_version=$(cat .ruby-version)" >> $GITHUB_OUTPUT
          echo "bundler_version=$(grep -A 1 'BUNDLED WITH' Gemfile.lock | tail -n1 | xargs)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: web.Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            RUBY_VERSION=${{ steps.versions.outputs.ruby_version }}
            BUNDLER_VERSION=${{ steps.versions.outputs.bundler_version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
